name: Publish Atmoos.World.IO

on:
  pull_request:
    types: [closed]
    branches: [ "main" ]
    paths: 
      - '**/Atmoos.World.IO.csproj'

jobs:
  publish-world:

    permissions:
      contents: write

    uses: ./.github/workflows/publish-library.yml
    with:
      project-path: 'source/Atmoos.World.IO/Atmoos.World.IO.csproj'
      tag-prefix: 'world.io'
    secrets: inherit
